export const modulosEnum = Object.freeze({
  HOME: "HOME",
  CLIENTES: "CLIENTES",
  ANIMAIS: "ANIMAIS",
  COMERCIAL: "COMERCIAL",
  AGENDA: "AGENDA",
  SERVICOS: "SERVICOS",
  PRODUTOS: "PRODUTOS",
  COLABORADORES: "COLABORADORES",
  CAIXA: "CAIXA",
  USUARIOS: "USUARIOS",
  SAIR: "SAIR"

});